CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

INCLUDE(ExternalProject)


FUNCTION(BUILD_ODEINT BUILD_DIR)

  SET(ODEINT_SRC ${BUILD_DIR}/src)

  EXTERNALPROJECT_ADD(
    odeint-v2
    GIT_REPOSITORY https://github.com/headmyshoulder/odeint-v2.git
    GIT_TAG 540f46f42cf1cd80f1dbfe0e6c1efa4bb70b2d6c
    SOURCE_DIR ${ODEINT_SRC}
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
  )

  SET(ODEINT_INCLUDE_DIRS ${BUILD_DIR}/src/include PARENT_SCOPE)

  ADD_DEPENDENCIES(DEPS odeint-v2)

ENDFUNCTION(BUILD_ODEINT)
