CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

INCLUDE(ExternalProject)


FUNCTION(BUILD_MULTIPRECISION BUILD_DIR)

  SET(MULTIPRECISION_SRC ${BUILD_DIR}/src)

  EXTERNALPROJECT_ADD(
    boost_multiprecision
    GIT_REPOSITORY https://github.com/boostorg/multiprecision.git
    GIT_TAG 339085567bcc3911b0c194bf5afc13f60c388831
    SOURCE_DIR ${MULTIPRECISION_SRC}
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
  )

  SET(MULTIPRECISION_INCLUDE_DIRS ${BUILD_DIR}/src/include PARENT_SCOPE)

  ADD_DEPENDENCIES(DEPS boost_multiprecision)

ENDFUNCTION(BUILD_MULTIPRECISION)
