CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

INCLUDE(ExternalProject)


FUNCTION(BUILD_CLN BUILD_DIR INSTALL_PREFIX)

  SET(CLN_SRC ${BUILD_DIR}/src)
  SET(CLN_BIN ${BUILD_DIR}/bin)
  SET(CLN_INSTALL ${INSTALL_PREFIX})
  SET(CLN_INSTALL ${INSTALL_PREFIX} PARENT_SCOPE)

  EXTERNALPROJECT_ADD(
    CLN
    DOWNLOAD_COMMAND wget http://www.ginac.de/CLN/cln-1.3.4.tar.bz2 && tar xvf cln-1.3.4.tar.bz2 -C ${CLN_SRC} --strip-components=1

    SOURCE_DIR ${CLN_SRC}
    BINARY_DIR ${CLN_BIN}

    CONFIGURE_COMMAND ${CLN_SRC}/configure --quiet --prefix=${CLN_INSTALL}
    BUILD_COMMAND make
    INSTALL_COMMAND make install
  )

  SET(CLN_FOUND PARENT_SCOPE)

  SET(CLN_INCLUDE_DIR ${CLN_INSTALL}/include)
  SET(CLN_INCLUDE_DIR ${CLN_INCLUDE_DIR} PARENT_SCOPE)
  SET(CLN_INCLUDE_DIRS ${CLN_INCLUDE_DIR} PARENT_SCOPE)

  SET(CLN_LIBRARY ${CLN_INSTALL}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}cln${CMAKE_STATIC_LIBRARY_SUFFIX})
  SET(CLN_LIBRARY ${CLN_LIBRARY} PARENT_SCOPE)
  SET(CLN_LIBRARIES ${CLN_LIBRARY} PARENT_SCOPE)

  SET(CLN_LIBRARY_DIR ${CLN_INSTALL}/lib)
  SET(CLN_LIBRARY_DIR ${CLN_LIBRARY_DIR} PARENT_SCOPE)
  SET(CLN_LIBRARY_DIRS ${CLN_LIBRARY_DIR} PARENT_SCOPE)

  ADD_DEPENDENCIES(DEPS CLN)

ENDFUNCTION(BUILD_CLN)


FUNCTION(BUILD_GINAC BUILD_DIR CLN_INCLUDE_DIRS CLN_LIBRARY_DIRS CLN_LIBRARIES INSTALL_PREFIX)

  SET(GINAC_SRC ${BUILD_DIR}/src)
  SET(GINAC_BIN ${BUILD_DIR}/bin)
  SET(GINAC_INSTALL ${INSTALL_PREFIX})
  SET(GINAC_INSTALL ${INSTALL_PREFIX} PARENT_SCOPE)

  SET(CUSTOM_PKGCONFIG ${CLN_LIBRARY_DIRS}/pkgconfig)

  EXTERNALPROJECT_ADD(
    GiNaC
    DEPENDS CLN
    DOWNLOAD_COMMAND wget https://www.ginac.de/ginac-1.7.2.tar.bz2 && tar xvf ginac-1.7.2.tar.bz2 -C ${GINAC_SRC} --strip-components=1

    SOURCE_DIR ${GINAC_SRC}
    BINARY_DIR ${GINAC_BIN}

    # pkg-config needs a nudge to find the installed version of CLN
    CONFIGURE_COMMAND ${GINAC_SRC}/configure --quiet --prefix=${GINAC_INSTALL} PKG_CONFIG_PATH=${CUSTOM_PKGCONFIG}
    BUILD_COMMAND make
    INSTALL_COMMAND make install
  )

  SET(GINAC_FOUND PARENT_SCOPE)

  SET(GINAC_INCLUDE_DIR ${GINAC_INSTALL}/include)
  SET(GINAC_INCLUDE_DIR ${GINAC_INCLUDE_DIR} PARENT_SCOPE)
  SET(GINAC_INCLUDE_DIRS ${GINAC_INCLUDE_DIR} ${CLN_INCLUDE_DIRS} PARENT_SCOPE)

  SET(GINAC_LIBRARY ${GINAC_INSTALL}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}ginac${CMAKE_STATIC_LIBRARY_SUFFIX})
  SET(GINAC_LIBRARY ${GINAC_LIBRARY} PARENT_SCOPE)
  SET(GINAC_LIBRARIES ${GINAC_LIBRARY} ${CLN_LIBRARIES} PARENT_SCOPE)

  SET(GINAC_LIBRARY_DIR ${GINAC_INSTALL}/lib)
  SET(GINAC_LIBRARY_DIR ${GINAC_LIBRARY_DIR} PARENT_SCOPE)
  SET(GINAC_LIBRARY_DIRS ${GINAC_LIBRARY_DIR} ${CLN_LIBRARY_DIRS})

  ADD_DEPENDENCIES(DEPS GiNaC)

ENDFUNCTION(BUILD_GINAC)
