CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

INCLUDE(ExternalProject)


FUNCTION(BUILD_CLN BUILD_DIR INSTALL_PREFIX)

  SET(CLN_SRC ${BUILD_DIR}/src)
  SET(CLN_BIN ${BUILD_DIR}/bin)
  SET(CLN_INSTALL ${INSTALL_PREFIX})
  SET(CLN_INSTALL ${INSTALL_PREFIX} PARENT_SCOPE)

  EXTERNALPROJECT_ADD(
    CLN
    URL http://www.ginac.de/CLN/cln-1.3.4.tar.bz2
    URL_MD5 30ef9d2f02ef5c3f8d221a8692f8b28e

    SOURCE_DIR ${CLN_SRC}
    BINARY_DIR ${CLN_BIN}

    CONFIGURE_COMMAND ${CLN_SRC}/configure --quiet --prefix=${CLN_INSTALL}
    BUILD_COMMAND make
    INSTALL_COMMAND make install
  )

  SET(CLN_FOUND PARENT_SCOPE)

  SET(CLN_INCLUDE_DIR ${BUILD_DIR}/src/include)
  SET(CLN_INCLUDE_DIR ${CLN_INCLUDE_DIR} PARENT_SCOPE)
  SET(CLN_INCLUDE_DIRS ${CLN_INCLUDE_DIR} PARENT_SCOPE)

  SET(CLN_LIBRARY ${CLN_INSTALL}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}cln${CMAKE_STATIC_LIBRARY_SUFFIX})
  SET(CLN_LIBRARY ${CLN_LIBRARY} PARENT_SCOPE)
  SET(CLN_LIBRARIES ${CLN_LIBRARY} PARENT_SCOPE)

  SET(CLN_LIBRARY_DIR ${CLN_INSTALL}/lib)
  SET(CLN_LIBRARY_DIR ${CLN_LIBRARY_DIR} PARENT_SCOPE)
  SET(CLN_LIBRARY_DIRS ${CLN_LIBRARY_DIR} PARENT_SCOPE)

  ADD_DEPENDENCIES(DEPS CLN)

ENDFUNCTION(BUILD_CLN)


FUNCTION(BUILD_GINAC BUILD_DIR CLN_INCLUDE_DIRS CLN_LIBRARY_DIRS CLN_LIBRARIES INSTALL_PREFIX)

  SET(GINAC_SRC ${BUILD_DIR}/src)
  SET(GINAC_BIN ${BUILD_DIR}/bin)
  SET(GINAC_INSTALL ${INSTALL_PREFIX})
  SET(GINAC_INSTALL ${INSTALL_PREFIX} PARENT_SCOPE)

  EXTERNALPROJECT_ADD(
    GiNaC
    DEPENDS CLN
    URL http://www.ginac.de/ginac-1.7.2.tar.bz2
    URL_MD5 ac47d481ef8f7ce423ac226fb07e9359

    SOURCE_DIR ${GINAC_SRC}
    BINARY_DIR ${GINAC_BIN}

    # should find CLN installation under prefix
    CONFIGURE_COMMAND ${GINAC_SRC}/configure --quiet --prefix=${GINAC_INSTALL}
    BUILD_COMMAND make
    INSTALL_COMMAND make install
  )

  SET(GINAC_FOUND PARENT_SCOPE)

  SET(GINAC_INCLUDE_DIR ${BUILD_DIR}/src/include)
  SET(GINAC_INCLUDE_DIR ${GINAC_INCLUDE_DIR} PARENT_SCOPE)
  SET(GINAC_INCLUDE_DIRS ${CLN_INCLUDE_DIRS} ${GINAC_INCLUDE_DIR} PARENT_SCOPE)

  SET(GINAC_LIBRARY ${GINAC_INSTALL}/lib/${CMAKE_FIND_LIBRARY_PREFIXES}ginac${CMAKE_STATIC_LIBRARY_SUFFIX})
  SET(GINAC_LIBRARY ${GINAC_LIBRARY} PARENT_SCOPE)
  SET(GINAC_LIBRARIES ${CLN_LIBRARIES} ${GINAC_LIBRARY} PARENT_SCOPE)

  SET(GINAC_LIBRARY_DIR ${GINAC_INSTALL}/lib)
  SET(GINAC_LIBRARY_DIR ${GINAC_LIBRARY_DIR} PARENT_SCOPE)
  SET(GINAC_LIBRARY_DIRS ${CLN_LIBRARY_DIRS} ${GINAC_LIBRARY_DIR})

  ADD_DEPENDENCIES(DEPS GiNaC)

ENDFUNCTION(BUILD_GINAC)
