CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

INCLUDE(ExternalProject)


FUNCTION(BUILD_ODEINT BUILD_DIR)

  SET(ODEINT_SRC ${BUILD_DIR}/src)

  EXTERNALPROJECT_ADD(
    odeint-v2
    GIT_REPOSITORY https://github.com/ds283/odeint-v2.git
    GIT_TAG af59be4beb759929a78ccfe17db8b64b194f36b0
    SOURCE_DIR ${ODEINT_SRC}
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
  )

  SET(ODEINT_INCLUDE_DIRS ${BUILD_DIR}/src/include PARENT_SCOPE)

  ADD_DEPENDENCIES(DEPS odeint-v2)

ENDFUNCTION(BUILD_ODEINT)
