FIND_PATH(CPPTRANSPORT_INCLUDE_DIR transport-runtime-api/transport.h)
FIND_PATH(CPPTRANSPORT_JSONCPP_INCLUDE_DIR json/json.h)
FIND_PATH(CPPTRANSPORT_SPLINTER_INCLUDE_DIR SPLINTER/bspline.h)


FIND_LIBRARY(CPPTRANSPORT_SPLINTER_LIBRARY NAMES splinter-static-2-0)
FIND_LIBRARY(CPPTRANSPORT_JSONCPP_LIBRARY NAMES jsoncpp)


SET(CPPTRANSPORT_INCLUDE_DIRS
  ${CPPTRANSPORT_INCLUDE_DIR}
  ${CPPTRANSPORT_JSONCPP_INCLUDE_DIR}
  ${CPPTRANSPORT_SPLINTER_INCLUDE_DIR}/SPLINTER
  ${CPPTRANSPORT_SPLINTER_INCLUDE_DIR}
)


SET(CPPTRANSPORT_LIBRARIES
  ${CPPTRANSPORT_SPLINTER_LIBRARY}
  ${CPPTRANSPORT_JSONCPP_LIBRARY}
)


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CppTransport DEFAULT_MSG
  CPPTRANSPORT_INCLUDE_DIR
  CPPTRANSPORT_JSONCPP_INCLUDE_DIR
  CPPTRANSPORT_SPLINTER_INCLUDE_DIR
  CPPTRANSPORT_SPLINTER_LIBRARY
  CPPTRANSPORT_JSONCPP_LIBRARY
)


MARK_AS_ADVANCED(
  CPPTRANSPORT_INCLUDE_DIR
  CPPTRANSPORT_JSONCPP_INCLUDE_DIR
  CPPTRANSPORT_SPLINTER_INCLUDE_DIR
  CPPTRANSPORT_SPLINTER_LIBRARY
  CPPTRANSPORT_JSONCPP_LIBRARY
)
