FIND_PATH(CPPTRANSPORT_INCLUDE_DIR transport-runtime-api/transport.h)


SET(CPPTRANSPORT_INCLUDE_DIRS
  ${CPPTRANSPORT_INCLUDE_DIR}
  )


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CppTransport DEFAULT_MSG CPPTRANSPORT_INCLUDE_DIR)


MARK_AS_ADVANCED(CPPTRANSPORT_INCLUDE_DIR)
